# Which docker image should be used to deploy
DOCKER_TAG: ""
# This option turns on or off logging in graylog
GRAYLOG_ON: "false"
# This option turns on or off kafka enable
KAFKA_ENABLE: "false"
KAFKA_REPORTING_SERVERS: ""
# Keycloak enabled
KEYCLOAK_ENABLED: "false"
# IP of db
PG_DB_ADDR: "my-postgres-postgresql"
# Spring profile for security
SPRING_PROFILES: "disable-security"
keepHookLogs: true
HELPER_IMAGE: "ghcr.io/netcracker/qubership-testing-platform-helm-hook-helper:main_latest"
CONTENT_SECURITY_POLICY: "*"
pg_pass: "postgrestest"
pg_user: "postgres"
DATASET_GRIDFS_ENABLED: "false"
EI_GRIDFS_ENABLED: "false"
HAZELCAST_ENABLE: false
EI_CLEAN_JOB_ENABLED: "false"
JAVERS_ENABLED: "false"
SERVICE_ENTITIES_MIGRATION_ENABLED: "false"
KAFKA_SERVERS: "false"
SERVICE_HOSTNAME: "http://atp-datasets.datasets.svc.cluster.local"